logo_title: 一只小沙雕

style: white

favicon: /favicon.png

menu:
  归档: /archives
  标签: /tags
  友链: /links
  关于: /about

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: 7ByH9IdUWj94bKIkOBlAK2jQ-gzGzoHsz
  appKey: lFpFD6ARU8Xwpbl5w4xYQwVk

highlight:
  enable: true


cdn:
  enabled: false
  url: https://cdn.jsdelivr.net/gh/journey-ad/nocilol.me

analytics:
  googleId: UA-71903189-1
